version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
  database:
    container_name: db
    build: ./database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kukurydza12
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d