version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kukurydza12
      POSTGRES_DB: health-insurance-app
    volumes:
      - ./data:/var/lib/postgresql/data